### ISSUE TITLE
[BUG] Control always displayed 

### ISSUE THREAD

**Issue by blackraven96** [jhomlala/betterplayer#650] opened 2021-08-16 14:27 UTC
Hi,

When I use the player with a live stream, controls stay always displayed. I can't remove them.

Thx.

**Comment by jhomlala** [comment] 2021-08-16 20:08
@blackraven96 Please follow issue template and provide all necessary details.

**Comment by jhomlala** [comment] 2021-08-16 20:40
I've did simple test with `liveStream' flag on and controls UI show/hide correctly.
```dart
import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:flutter/material.dart';

class NormalPlayerPage extends StatefulWidget {
  @override
  _NormalPlayerPageState createState() => _NormalPlayerPageState();
}

class _NormalPlayerPageState extends State<NormalPlayerPage> {
  late BetterPlayerController _betterPlayerController;
  late BetterPlayerDataSource _betterPlayerDataSource;

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
      autoPlay: true,
      looping: true,
    );
    _betterPlayerDataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      Constants.forBiggerBlazesUrl,
      liveStream: true
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(_betterPlayerDataSource);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Normal player page"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(controller: _betterPlayerController),
          ),
        ],
      ),
    );
  }
}

```

Anyway @blackraven96 please provide **minimal reproducible example**.

**Comment by Tha14** [comment] 2021-08-18 22:44
Hi, I am also having the exact same issue on Android. The controls follow the 'controlsHideTime' duration but while they are fading away the pop back up and stay visible regardless.

I also want to point out that I am using "com.google.android.exoplayer:extension-rtmp:2.14.2" since I am playing a stream through RTMP. I don't know whether the OP is also using it. I did not create an issue as I though it was a buffering problem since I use RTMP.

This is the configuration for the player that I am using:

```
betterPlayerConfiguration = BetterPlayerConfiguration(fit: BoxFit.contain,
      autoPlay: true,
      fullScreenByDefault: true,
      deviceOrientationsAfterFullScreen: const [DeviceOrientation.portraitUp],
      controlsConfiguration: const BetterPlayerControlsConfiguration(
        controlsHideTime: const Duration(milliseconds: 150),
        enableSkips: false,
        enableOverflowMenu: false,
      ),
);

_betterPlayerDataSource = BetterPlayerDataSource(
  BetterPlayerDataSourceType.network,
  widget._url,
  cacheConfiguration: BetterPlayerCacheConfiguration(
    useCache: false,
  ),
  notificationConfiguration: BetterPlayerNotificationConfiguration(showNotification: true, title: title_live, author: "COCKTAIL Live", imageUrl: imageUrl),
  liveStream: true,
);


    _LivebetterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _LivebetterPlayerController.setupDataSource(_betterPlayerDataSource);
```

**Comment by KAPILBADWAL** [comment] 2021-08-20 07:30
Hi,
I am facing the same issue while playing live stream.
Even with the liveStream flag set as true and the sample code shared by @jhomlala , the issue is still there. Control options are always getting displayed.
I am playing a MPEG TS (H.264+MP3) stream.

**Comment by Tha14** [comment] 2021-08-20 12:00
> r

I am using the same settings for encoding the stream. It also appears to happen without having the livestream: true flag but still using the same stream url. I have not looked into the package's code but is it possible that it tries to display or calculate the time remaining and fails due to http response flags or the encoded file info?

**Comment by jhomlala** [comment] 2021-08-25 16:16
Can you provide sample video? I need to reproduce it on my side.

**Comment by jhomlala** [comment] 2021-09-20 19:27
Fixed in 0.0.74.

**Closed by jhomlala** 2021-09-20 19:27 UTC
Labels: bug

**Comment by leanhro2812** [comment] 2022-06-24 17:57
Same issue 0.0.83

**Comment by josephmazigo** [comment] 2022-07-20 22:08
same issue 0.0.83 @jhomlala

**Comment by mscaster** [comment] 2024-08-19 12:41
Same issue
