### ISSUE TITLE
Exception after fullscreen video

### ISSUE THREAD

**Issue by dvirgiln** [jhomlala/betterplayer#194] opened 2021-01-03 18:09 UTC
**Describe the bug**
After clicking on Full Screen, and then go back to normal view, then appears a message the video cannot be player. 
After refreshing the same view, it appears the same error on the player. 

There is an exception:

I/OMXClient( 4794): IOmx service obtained
W/MediaCodecRenderer( 4794): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 4794):   android.media.MediaCodec$CodecException: Error 0xfffffff4
W/MediaCodecRenderer( 4794):       at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer( 4794):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
W/MediaCodecRenderer( 4794):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
W/MediaCodecRenderer( 4794):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
W/MediaCodecRenderer( 4794):       at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer( 4794):       at android.os.Looper.loop(Looper.java:225)
W/MediaCodecRenderer( 4794):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4794): Playback error
E/ExoPlayerImplInternal( 4794):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.892057], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal( 4794):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 4794):       at android.os.Looper.loop(Looper.java:225)
E/ExoPlayerImplInternal( 4794):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4794):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.892057], [-1, -1])
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal( 4794):       ... 3 more
E/ExoPlayerImplInternal( 4794):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal( 4794):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal( 4794):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
E/ExoPlayerImplInternal( 4794):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
E/ExoPlayerImplInternal( 4794):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
E/ExoPlayerImplInternal( 4794):       ... 10 more
E/flutter ( 4794): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 29.892057], [-1, -1]), format_supported=YES, null, null)
E/flutter ( 4794): 
**Better Player version**
- Version: latest 0.0.34

**Smartphone (please complete the following information):**
 - Android (Xiaomi Redmi 8)

**Additional context**

**Comment by jhomlala** [comment] 2021-01-06 09:58
You're using old Better Player version. Please upgrade to 0.0.43 and try again.
Also this issue is duplicate of https://github.com/jhomlala/betterplayer/issues/27

**Comment by jhomlala** [comment] 2021-01-09 14:53
Closed due to no activity. Feel free to anwser in this issue and I'll reopen it.

**Closed by jhomlala** 2021-01-09 14:53 UTC
Labels: info required
