### ISSUE TITLE
[BUG] Player fails to initialize when multiple videos are loaded simultaneously

### ISSUE THREAD

**Issue by ashishbeck** [jhomlala/betterplayer#314] opened 2021-02-20 11:57 UTC
**Describe the bug**
I'm building a vertical scrolling short video app using the BetterPlayerListVideoPlayer and preloading 5 instances of the player at a time which get loaded as the user scrolls down the [PreloadPageView](https://pub.dev/packages/preload_page_view). So I'm assuming there are at least 10 instances of the video player at any given point of time. After scrolling for a while, this error is thrown and the video shows the error screen.
```
E/ExoPlayerImplInternal( 5190): Playback error
E/ExoPlayerImplInternal( 5190):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [576, 1024, 29.967804], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal( 5190):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 5190):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal( 5190):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5190):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [576, 1024, 29.967804], [-1, -1])
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal( 5190):       ... 3 more
E/ExoPlayerImplInternal( 5190):   Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 5190):       at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 5190):       at android.media.MediaCodec.<init>(MediaCodec.java:1876)
E/ExoPlayerImplInternal( 5190):       at android.media.MediaCodec.createByCodecName(MediaCodec.java:1848)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1127)
E/ExoPlayerImplInternal( 5190):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
E/ExoPlayerImplInternal( 5190):       ... 10 more
I/flutter ( 5190): error found in video with buffer = 10 and id = 10
I/flutter ( 5190): {exception: Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [576, 1024, 29.967804], [-1, -1]), format_supported=YES}
E/flutter ( 5190): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [576, 1024, 29.967804], [-1, -1]), format_supported=YES, null, null)
```

**To Reproduce**
1. Create a ListView with BetterPlayerListVideoPlayer (or use the preload page view as I did with preload count = 5) having a large number of videos loaded through network.
2. Scroll down some videos

**Expected behavior**
The videos should be played as they appear in view

**Flutter doctor**
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.6 at C:\Flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Ashish\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Ashish\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • SM A505F (mobile) • 192.168.1.3:5555 • android-arm64 • Android 10 (API 29)

• No issues found!

```

**Better Player version**
- Version: 0.0.55

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 10

**Comment by jhomlala** [comment] 2021-02-20 12:12
Duplicate of https://github.com/jhomlala/betterplayer/issues/27

Each android device has limit of max ExoPlayer instances that can be created. You need to re-use instances. Check this example: https://github.com/jhomlala/betterplayer/tree/master/example/lib/pages/reusable_video_list

Reuse of Better Player instance is the only way to handle this scenario.

**Closed by jhomlala** 2021-02-20 12:12 UTC
Labels: new issue
