### ISSUE TITLE
[FEATURE] Chromecast, Resize Subtile, Color Subtile

### ISSUE THREAD

**Issue by avinh** [jhomlala/betterplayer#297] opened 2021-02-12 17:27 UTC
1. Connect an phone to TV 
2. Resize Subtile
3. Change color subtile
4. View preview video 
5. Do not let sleep screen while playing (small screen, not full screen)

**Comment by jhomlala** [comment] 2021-02-12 18:42
@avinh please fill issue template properly. You didn't provide all necessary information. How are you connecting phone to TV? Is this reproducible on simulator?

**Comment by avinh** [comment] 2021-02-12 22:46
You can play videos on TV through your phone
Detail:
https://www.google.com/chromecast/built-in/learn/tv/
Package support chromecast for flutter:
https://pub.dev/packages/flutter_vlc_player
I hope you can support it in better player, thanks

**Comment by jhomlala** [comment] 2021-02-13 22:17
I don't have access to chromecast right now. Can you tell if it's possible to use some simulator/emulator to reproduce this behavior without physical device?

**Comment by jhomlala** [comment] 2021-02-14 09:25
Seems like duplicate of https://github.com/jhomlala/betterplayer/issues/64. Please continue discussion in this issue.

**Closed by jhomlala** 2021-02-14 09:25 UTC
Labels: info required
