### ISSUE TITLE
[FEATURE]Can support dencrypte AES-128 for hls

### ISSUE THREAD

**Issue by YeFei572** [jhomlala/betterplayer#277] opened 2021-02-07 03:30 UTC
**Is your feature request related to a problem? Please describe.**
I have a question about the hls stream player that I need to ask. Playing stream m3u8 requires AES-128 decoding operation, does this component support it?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jhomlala** [comment] 2021-02-07 08:20
Duplicate of: https://github.com/jhomlala/betterplayer/issues/155

Right now content protection is not available.

**Closed by jhomlala** 2021-02-07 08:20 UTC
Labels: enhancement, new issue

**Comment by mayank250004** [comment] 2022-08-14 20:44
How to play stream m3u8 requires AES-128 decoding operation.
