### ISSUE TITLE
[BUG]Full screen: Keep playing if you app goes in background.

### ISSUE THREAD

**Issue by ishaan-puniani** [jhomlala/betterplayer#206] opened 2021-01-09 21:15 UTC
**Describe the bug**
When I play a video and switch to full screen, then use back key of andriod to navigate to android home view.
Observe that the sound keeps playing for the video in the background. Now open the app again and you are able to start a new instance of video (Audio from the previous instance is still on going). Now 1 video and 2 audios are playing at different timeline

**To Reproduce**
1. Configure video from network.  
2. Click on 'Full Screen Icon'.
3. Use back key of android multiple times to navigate to home screen of android.
4. Observe audio keeps on playing in the background app

**Expected behavior**
Video Player should get disposed and Audio should be stopped.

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version: 0.0.44 (Latest)

**Smartphone (please complete the following information):**
 - Device: [Samsung S9]
 - OS: [Android Latest]

**Additional context**
I have just tried the example documented at https://pub.dev/packages/better_player
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Example player"),
      ),
      body: AspectRatio(
        aspectRatio: 16 / 9,
        child: BetterPlayer.network(
          "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
          betterPlayerConfiguration: BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
          ),
        ),
      ),
    );
  }

```

**Comment by jhomlala** [comment] 2021-01-10 08:03
@ishaan-puniani I can't reproduce it on my side. Is this reproducible 100% each time? Is there any error in console (if yes, share stacktrace in comment).

**Comment by ishaan-puniani** [comment] 2021-01-10 18:35
Hello, for me it is reproducible each time. As such there is no error logged in the logcat. I will try to see if something is logged as verbose.

**Comment by ishaan-puniani** [comment] 2021-01-11 00:06
Well does it get impacted if I enable multiDex? I have integrated flutter fire for Authentication in the app.

**Comment by jhomlala** [comment] 2021-01-14 18:55
Can you try run better player example https://github.com/jhomlala/betterplayer/tree/master/example and see if this problem happens?

**Comment by ishaan-puniani** [comment] 2021-01-20 00:29
Yes, I have tried it as per example and also troubleshooted a bit.
The issue is in development phase, when I am making some changes in the widget, the hot reloading get  triggered and my guess it at that time dispose cycle is not executed in the way it should be.

As of now the issue is not reproducible when I build the app and use it as a user.

**Comment by jhomlala** [comment] 2021-01-23 21:11
So seems like this issue occurs only when you're doing hot reloads. I'll close it, but feel free to answer and I'll reopen it.

**Closed by jhomlala** 2021-01-23 21:11 UTC
Labels: bug, info required
