### ISSUE TITLE
[FEATURE]How the player shows the duration of time and Remaining time.

### ISSUE THREAD

**Issue by peterbyCom** [jhomlala/betterplayer#366] opened 2021-03-03 08:17 UTC
Hello. sir.

The player is currently running normally, thank you for your contribution, but I have a question.

I want it to show the duration of the video. Just like HTML5 videojs,

How do i define settings?

**Comment by jhomlala** [comment] 2021-03-03 17:04
Duplicate of https://github.com/jhomlala/betterplayer/issues/304.

**Closed by jhomlala** 2021-03-03 17:04 UTC
Labels: enhancement, new issue
