### ISSUE TITLE
Question: When video is paused --> show picture that was last shown on iOS

### ISSUE THREAD

**Issue by MiroLiebschner** [jhomlala/betterplayer#126] opened 2020-11-10 10:23 UTC
As I own no iPhone I can't reproduce the error to test & fix it. 
Problem:
When I pause on Android the video just stops, the picture that was shown when the movie stopped is still shown. 
On iOS the tester told me that the video turns black when paused. As I expect that the error is within my code I wanted to ask if smb knows which part of the code / argument is responsible to show the correct picture when paused on iOS.

**Comment by jhomlala** [comment] 2020-11-15 19:03
Since this issue is not following issue template, I'll mark it as duplicate of this issue: https://github.com/jhomlala/betterplayer/issues/132

Please use issue template next time. Also please watch issue above for future solution.

**Closed by jhomlala** 2020-11-15 19:03 UTC
Labels: new issue
