### ISSUE TITLE
 [BUG] Video overlapping problem in HLS format.  

### ISSUE THREAD

**Issue by shreytechtonic** [jhomlala/betterplayer#308] opened 2021-02-18 12:07 UTC
**Describe the bug**
In HLS format while changing the video quality, small video (say 360x640 ) overlaps on the bigger video file(say 1920x720). 

**To Reproduce**
Please look at the attached file to reproduce the problem. Just change the extension from .txt to .dart. 
[main.txt](https://github.com/jhomlala/betterplayer/files/6002600/main.txt)

**Screenshots**

![Screenshot_1613649129](https://user-images.githubusercontent.com/73583205/108354440-73ee3900-720f-11eb-9010-b403009acde9.png)
![Screenshot_1613648225](https://user-images.githubusercontent.com/73583205/108354486-84061880-720f-11eb-9784-a5ef1d6f591c.png)
![Screenshot_1613648142](https://user-images.githubusercontent.com/73583205/108354513-8ec0ad80-720f-11eb-8b50-0502de5a0712.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_IN)
    • Flutter version 1.22.5 at /home/shrey/flutter
    • Framework revision 7891006299 (2 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/shrey/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+9-Ubuntu-0ubuntu1.18.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

**Better Player version**
-0.0.55 Version:

**Smartphone (please complete the following information):**
Android Emulator Pixel 4XL API 30

**Comment by jhomlala** [comment] 2021-02-20 22:33
I agree this strange issue, seems like something connected with texture entry and surface on native Android. I did some research, but couldn't find a way to clear surface after changing track. If anyone know what's the cause of this issue and how to handle it, please let me know.

**Comment by shreytechtonic** [comment] 2021-02-21 17:11
Hi @jhomlala firstly thank you for creating this plugin, this solves many problems which other players have and it is indeed better than chewie, 
I was testing another plugin which is yoyo_player https://pub.dev/packages/yoyo_player, this solves the overlapping problem, maybe this can help.

**Comment by dc480506** [comment] 2021-02-23 08:44
@jhomlala Even I'm having this issue but it seems to be on Android 7.1.1 and below ... I tested it on Android 9 and there's no such issue of overlapping.

**Comment by jhomlala** [comment] 2021-02-23 20:11
yoyo_player uses video_player underhood. Better_player uses modified version of video_player. This task requires more debugging, but right now I don't have enough spare time for this. Will look into this in near future.

**Comment by jhomlala** [comment] 2021-02-23 20:18
When someone changes video quality in yoyo, then new video controller will be initialised. This is bad way, it should be changed with track selector just like Better Player. Creating new controller just like yoyo doing will lead to Exo Player decoder issues.

**Comment by chmiguel** [comment] 2021-03-12 05:30
I'm experiencing this issue when the network goes slow and player automatically reduces the quality. If anyone has a solution I'll be completely thankful

**Comment by vanfresh** [comment] 2021-03-15 11:02
I am experiencing this issue as well.  Seems to be frequently encountered on Android.

**Comment by jhomlala** [comment] 2021-04-13 19:17
I've retested this issue with latest Flutter version:

```dart
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)
```

Seems like issue is gone. I've tested in both real device and emulator. If anyone have reproducible example with latest stable version of Flutter please let me know in this issue.

**Closed by jhomlala** 2021-04-13 19:17 UTC
Labels: bug, help wanted

**Comment by brightchip** [comment] 2022-08-10 01:36
How did you guys fix that ?
