### ISSUE TITLE
[BUG] video had green background and very small plus black screen on Android tv

### ISSUE THREAD

**Issue by kreativeteksolutions** [jhomlala/betterplayer#658] opened 2021-08-20 23:10 UTC
**History check**
Checked for other issues relating to mine and did not find anything before posting this.

**Describe the bug**
The video doesn't properly fill the screen on a Firestick.

**Example code*

when the page starts up:
`url =
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4";
    src = BetterPlayerDataSource(BetterPlayerDataSourceType.network, url);

    betterController = BetterPlayerController(
        BetterPlayerConfiguration(
          autoPlay: true,
          looping: false,
          autoDispose: true,
        ),
        betterPlayerDataSource: src)`

how I have it implemented in the builder:
`AspectRatio(
                aspectRatio: 16 / 9,
                child: Container(
                  child: BetterPlayer(
                    controller: betterController,
                  ),
                ),
              ),`
**Debug Log*** 
```
I/ExoPlayerImpl(21627): Init c323b3 [ExoPlayerLib/2.14.2] [mantis, AFTMM, Amazon, 25]
D/MetadataUtil(21627): Skipped unknown metadata entry: gsst
D/MetadataUtil(21627): Skipped unknown metadata entry: gstd
D/MetadataUtil(21627): Skipped unknown metadata entry: gssd
D/MetadataUtil(21627): Skipped unknown metadata entry: gspu
D/MetadataUtil(21627): Skipped unknown metadata entry: gspm
D/MetadataUtil(21627): Skipped unknown metadata entry: gshh
I/OMXClient(21627): MuxOMX ctor
I/MediaCodec(21627): [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 22146051
I/MediaCodecLogger(21627): [ASAP] HW.video.avc P2 + 7968855
I/ACodec_vendorExt(21627): Setting OMX_IndexParamVideoHWComposed
W/ACodec_vendorExt(21627): Error OMX_IndexParamVideoHWComposed: Unknown error 1010 (1010)
I/ACodec  (21627): codec does not support config priority (err -1010)
I/MediaCodecLogger(21627): [ASAP] HW.video.avc P2 - 7968867
D/MediaCodecLogger(21627): Got a Service. Calling PID = 21627
I/MediaCodecLogger(21627): [ASAP] HW.video.avc P3 + 7968869
D/SurfaceUtils(21627): set up nativeWindow 0x82724008 for 1280x720, color 0x7f000001, rotation 0, usage 0x2933
W/ACodec  (21627): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 8 failed: -2147483648
W/ACodec  (21627): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 7 failed: -2147483648
I/MediaCodecLogger(21627): [ASAP] HW.video.avc P3 - 7968889
I/MediaCodecLogger(21627): [ASAP] HW.video.avc Got First Input Frame 7968890
I/OMXClient(21627): MuxOMX ctor
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a P2 + 7968905
I/ACodec  (21627): codec does not support config priority (err -2147483648)
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a P2 - 7968914
D/MediaCodecLogger(21627): Got a Service. Calling PID = 21627
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a P3 + 7968915
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a P3 - 7968920
W/ExoPlayer:Playb(21627): type=1400 audit(0.0:203): avc: denied { read } for name="u:object_r:dolby_prop:s0" dev="tmpfs" ino=12447 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:dolby_prop:s0 tclass=file permissive=0
W/ExoPlayer:Playb(21627): type=1400 audit(0.0:204): avc: denied { read } for name="u:object_r:dolby_prop:s0" dev="tmpfs" ino=12447 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:dolby_prop:s0 tclass=file permissive=0
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a Got First Input Frame 7968928
I/MediaCodecLogger(21627): updatePTSTime [SW.audio.mp4a] First PTS after Flush or reset = 0
I/MediaCodecLogger(21627): [ASAP] SW.audio.mp4a Got First Frame Ready 7968945
E/libc    (21627): Access denied finding property "dolby.dma.minbufcnt"
D/AudioTrack(21627): min buf count is limited to 2 times HAL buf
D/AmazonAudioTrackCallback(21627): No AudioTrackFlags provided.  Using internal defaults.
D/AmazonAudioTrackCallback(21627): No Audio content type provided.
I/android.media.AudioTrack(21627): AUDIOINFO: audio_input: format: 2 sample_rate: 44100 channels: 2 AudioAttributes: AudioAttributes: usage=1 content=3 flags=0x0 tags= bundle=null
E/libc    (21627): Access denied finding property "dolby.dma.minbufcnt"
D/AudioTrack(21627): min buf count is limited to 2 times HAL buf
D/AudioTrack(21627): Client defaulted notificationFrames to 3675 for frameCount 11025
W/AHierarchicalStateMachine(21627): Warning message AMessage(what = 'omxI') = {
W/AHierarchicalStateMachine(21627):   int32_t type = 0
W/AHierarchicalStateMachine(21627):   int32_t event = 3
W/AHierarchicalStateMachine(21627):   int32_t data1 = 1
W/AHierarchicalStateMachine(21627):   int32_t data2 = 117440527
W/AHierarchicalStateMachine(21627): } unhandled in root state.
D/SurfaceUtils(21627): set up nativeWindow 0x82724008 for 1920x1088, color 0x7f000001, rotation 0, usage 0x2933
W/ACodec  (21627): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 15 failed: -2147483648
W/ACodec  (21627): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 14 failed: -2147483648
I/MediaCodecLogger(21627): updateFormatChanged width = 1280 height = 720
I/MediaCodecLogger(21627): updatePTSTime [HW.video.avc] First PTS after Flush or reset = 0
I/MediaCodecLogger(21627): [ASAP] HW.video.avc Got First Frame Ready 7969041
I/MediaCodecLogger(21627): [ASAP] HW.video.avc Got First Frame Render 7969042
I/MediaCodecLogger(21627): App uses Timestamps for AVSync
I/art     (21627): Do full code cache collection, code=126KB, data=124KB
I/art     (21627): Starting a blocking GC JitCodeCache
I/art     (21627): After code cache collection, code=112KB, data=105KB
I/MediaCodecLogger(21627): 21627.HW.video.avc.bitrateInKbps = 2224
I/MediaCodecLogger(21627): updatePTSTime Possible seek found!
I/MediaCodecLogger(21627): 21627.SW.audio.mp4a.bitrateInKbps = 204
I/MediaCodecLogger(21627): 21627.HW.video.avc Resolution change from 0x0 to 1280x720 took = 0
I/MediaCodecLogger(21627): 21627.SW.audio.mp4a.bitrateInKbps = 133
```

**Expected behavior**
What is expected is to play the video properly and have it fill the screen. 

**Screenshots**
[https://imgur.com/cC9aCHj](https://imgur.com/cC9aCHj)

For some reason when I am playing this sample video on the FireStick I am getting a green screen around the video. At first, I thought it was a width/height issue but it seems it has something to do with the player itself. I have run this on an android tv emulator and it is working fine but I haven't had a chance to test it out on a real device. But regardless the scaling shouldn't be affected. 

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:^0.0.73

**Smartphone (please complete the following information):**
 - Device: Firestick
 - OS: Android 7.1

**Additional context**
[https://imgur.com/cC9aCHj](https://imgur.com/cC9aCHj)

***Update***

Tried it out on an Android based tv think it was android 10 and had a black screen

**Comment by jhomlala** [comment] 2021-08-22 17:26
@kreativeteksolutions Is there any way to reproduce this issue with some simulator? Without reproducible environment I'm unable to debug this issue.

Also from what I know, Amazon has forked ExoPlayer to solve "issues" on their devices. This may be reason why you're seeing this issue on your Amazon device. I don't have any plans to support this fork in Better Player. https://github.com/amzn/exoplayer-amazon-port

**Comment by kreativeteksolutions** [comment] 2021-08-22 17:32
> @kreativeteksolutions Is there any way to reproduce this issue with some simulator? Without reproducible environment I'm unable to debug this issue.
> 
> Also from what I know, Amazon has forked ExoPlayer to solve "issues" on their devices. This may be reason why you're seeing this issue on your Amazon device. I don't have any plans to support this fork in Better Player. https://github.com/amzn/exoplayer-amazon-port

If you try this on an Android tv version 7.1 or higher you will get a black screen. From what I understand it seems it's a h256 issue or what not.

**Comment by jhomlala** [comment] 2021-08-22 17:56
https://exoplayer.dev/supported-devices.html

```
Emulators - Some Android emulators do not properly implement components of Android’s media stack, and as a result do not support ExoPlayer. This is an issue with the emulator, not with ExoPlayer. Android’s official emulator (“Virtual Devices” in Android Studio) supports ExoPlayer provided the system image has an API level of at least 23. System images with earlier API levels do not support ExoPlayer. The level of support provided by third party emulators varies. Issues running ExoPlayer on third party emulators should be reported to the developer of the emulator rather than to the ExoPlayer team. Where possible, we recommend testing media applications on physical devices rather than emulators.
```

**Comment by kreativeteksolutions** [comment] 2021-08-22 18:26
> https://exoplayer.dev/supported-devices.html
> 
> 
> _Emulators - Some Android emulators do not properly implement components of Android’s media stack, and as a result do not support ExoPlayer. This is an issue with the emulator, not with ExoPlayer. Android’s official emulator (“Virtual Devices” in Android Studio) supports ExoPlayer provided the system image has an API level of at least 23. System images with earlier API levels do not support ExoPlayer. The level of support provided by third party emulators varies. Issues running ExoPlayer on third party emulators should be reported to the developer of the emulator rather than to the ExoPlayer team. Where possible, we recommend testing media applications on physical devices rather than emulators._
> 

I tested it out on a physical android tv. Not a emulator. I was just saying you may be able to reproduce the issue via an emulator.

**Comment by jhomlala** [comment] 2021-08-24 20:06
I need exactly the same Android TV as yours or emulator which can emulate same behavior. I don't have any "FireStick" device. Can you provide information how I can emulate this "FireStick" device? If not then I need to close this ticket because i won't be able to help you.

**Comment by kreativeteksolutions** [comment] 2021-08-24 20:07
> I need exactly the same Android TV as yours or emulator which can emulate same behavior. I don't have any "FireStick" device. Can you provide information how I can emulate this "FireStick" device? If not then I need to close this ticket because I won't be able to help you.

I will get back to you on this.

**Comment by jhomlala** [comment] 2021-09-07 18:30
No answer from author. Closing issue.

**Closed by jhomlala** 2021-09-07 18:30 UTC
Labels: info required
