### ISSUE TITLE
[FEATURE] Enter Fullscreen on Landscape and Exit Fullscreen on Portrait

### ISSUE THREAD

**Issue by FlatCodeIq** [jhomlala/betterplayer#671] opened 2021-08-27 17:30 UTC
**Is your feature request related to a problem? Please describe.**
I want the VideoPlayer to Enter Fullscreen when the phone is rotated horizontally and exit Fullscreen when the phone rotates to portrait. Exactly like Youtube.

**Describe the solution you'd like**
The VideoPlayer should detect the rotation and based on it, enters and exits the fullscreen (in addition to the fullscreen button in the controls)

**Describe alternatives you've considered**
I tried to listen to MediaQuery and do the logic myself. but it's very inefficient and collide with BetterPlayer Logic 

**Additional context**
NaN

**Comment by jhomlala** [comment] 2021-08-29 09:42
@FlatCodeIq Please use search function of Github. Duplicate of https://github.com/jhomlala/betterplayer/issues/117

**Closed by jhomlala** 2021-08-29 09:42 UTC
Labels: enhancement, new issue
