### ISSUE TITLE
[BUG] hls subtitle not working,and  movie do not fix to player

### ISSUE THREAD

**Issue by b14cknc0d3** [jhomlala/betterplayer#784] opened 2021-11-01 06:08 UTC
**Describe the bug**
[this hls type](https://liveorigin01.hbogoasia.com:8443/origin/live/main/HBO/index.m3u8)
do not fit to the player and it does not show subtitle
this [hls2](https://cdna02.gcdn.co/UpFiles/2021/10/24/42/202903/720p.m3u8) fit to the player screen but this has no subtitle itself.

**Example code*
```
class VideoPlayerPage extends StatefulWidget {
  final Movie movie;
  const VideoPlayerPage({Key? key, required this.movie}) : super(key: key);

  @override
  _VideoPlayerPageState createState() => _VideoPlayerPageState();
}

class _VideoPlayerPageState extends State<VideoPlayerPage> {
  late BetterPlayerController _betterPlayerController;
  late BetterPlayerDataSource _betterPlayerDataSource;

  @override
  void initState() {

    BetterPlayerConfiguration _betterPlayerConfiguration =
        BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      fit: BoxFit.contain,
      subtitlesConfiguration: BetterPlayerSubtitlesConfiguration(
        fontSize: 16.0,
      ),
      autoDispose: true,

      autoDetectFullscreenDeviceOrientation: true,
      controlsConfiguration: BetterPlayerControlsConfiguration(
          enableMute: true,
          enableOverflowMenu: true,

          showControlsOnInitialize: false,
          playerTheme: BetterPlayerTheme.material,
          enableProgressText: true),
    );

    _betterPlayerDataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      widget.movie.hdLink1,
      useAsmsSubtitles: true,

    );

    _betterPlayerController =
        BetterPlayerController(_betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(_betterPlayerDataSource);

    super.initState();
  }

  @override
  void dispose() {
    _betterPlayerController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

          return Scaffold(
            appBar: AppBar(),
            body: Column(
              mainAxisSize: MainAxisSize.max,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [

                Expanded(
                  child: AspectRatio(
                    aspectRatio: 16 / 9,
                    child: BetterPlayer(controller: _betterPlayerController),
                  ),
                )

              ], 
            ),
          );
        }
      },
    );
  }
}

```

**Expected behavior**
i want to show subtitle , and movie fit to player

**Screenshots**
[image](https://pasteboard.co/lgYocmWB4bDo.png)

**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/yelinaung/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/yelinaung/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69

**Better Player version**
- Version: 0.0.77

 - Device: [Pixel 4 ,api 30 emulator]

**Additional context**
hls subtitle not working, resolution, and movie do not fix to player

**Comment by jhomlala** [comment] 2021-11-04 21:31
@b14cknc0d3 
First data source is being displayed correctly on my device. I can't reproduce this issue.  On some devices there's similar issue with invalid resolution of the video. https://github.com/jhomlala/betterplayer/issues/768

Second data source has invalid SSL cert:
```
E/ExoPlayerImplInternal( 2410): Playback error
E/ExoPlayerImplInternal( 2410):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:596)
E/ExoPlayerImplInternal( 2410):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2410):       at android.os.Looper.loop(Looper.java:246)
E/ExoPlayerImplInternal( 2410):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 2410):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7705cc8c18: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 2410):   error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (external/boringssl/src/ssl/tls_record.cc:587 0x7725d41a58:0x00000001)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:358)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/ExoPlayerImplInternal( 2410):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 2410):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 2410):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal( 2410):   Caused by: javax.net.ssl.SSLHandshakeException: Read error: ssl=0x7705cc8c18: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 2410):   error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (external/boringssl/src/ssl/tls_record.cc:587 0x7725d41a58:0x00000001)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:919)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal( 2410):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:629)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:526)
E/ExoPlayerImplInternal( 2410):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:352)
E/ExoPlayerImplInternal( 2410):       ... 8 more
E/ExoPlayerImplInternal( 2410):   Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x7705cc8c18: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 2410):   error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (external/boringssl/src/ssl/tls_record.cc:587 0x7725d41a58:0x00000001)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal( 2410):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal( 2410):       ... 29 more
```
I'm unable to help you if your data source has invalid SSL cert.

**Comment by b14cknc0d3** [comment] 2021-11-05 05:17
what about subtitles for the first data source ? I can't get subtitles.

**Comment by jhomlala** [comment] 2021-11-06 21:38
Seems like stream is returning some invalid value:
```
I/flutter ( 7709): HttpException: Invalid header field name, with 32, uri = https://liveorigin01.hbogoasia.com:8443/origin/live/main/HBO/index.m3u8
I/flutter ( 7709): #0      _HttpParser._doParse (dart:_http/http_parser.dart:653:15)
I/flutter ( 7709): #1      _HttpParser._parse (dart:_http/http_parser.dart:324:7)
I/flutter ( 7709): #2      _HttpParser._onData (dart:_http/http_parser.dart:878:5)
I/flutter ( 7709): #3      _rootRunUnary (dart:async/zone.dart:1436:47)
I/flutter ( 7709): #4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 7709): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter ( 7709): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter ( 7709): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 7709): #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
I/flutter ( 7709): #9      _StreamController._add (dart:async/stream_controller.dart:607:7)
I/flutter ( 7709): #10     _StreamController.add (dart:async/stream_controller.dart:554:5)
I/flutter ( 7709): #11     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
I/flutter ( 7709): #12     _rootRunUnary (dart:async/zone.dart:1436:47)
I/flutter ( 7709): #13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter ( 7709): #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter ( 7709): #15     
```
This is something that can't be fixed on BP side.

**Comment by b14cknc0d3** [comment] 2021-11-09 03:48
on web player, it is working  .[web player link](https://www.hlsplayer.net/#type=m3u8&src=https%3A%2F%2Fliveorigin01.hbogoasia.com%3A8443%2Forigin%2Flive%2Fmain%2FHBO%2Findex.m3u8)

**Comment by jhomlala** [comment] 2021-12-29 09:42
It doesn't work for me.

**Closed by jhomlala** 2021-12-29 09:42 UTC
Labels: info required
