### ISSUE TITLE
[FEATURE] Auto full screen with device orientation

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [jhomlala/betterplayer#298] opened 2021-02-12 21:45 UTC
**Is your feature request related to a problem? Please describe.**
Yes, clicking the full screen button is not intuitive always. Most users expect the auto rotate functionality to work in any video player.

**Describe the solution you'd like**
adding a Boolean that allows the user to enable auto full screen with device orientation change. 

**Describe alternatives you've considered**
I tried using this package in the past for one of my apps and it had great support for auto full screen but couldn’t recreate it. 
https://pub.dev/packages/youtube_player_flutter
It works like a charm, the full screen functionality. If we could implement a similar thing that goes to full screen on orientation change?

**Additional context**

**Comment by jhomlala** [comment] 2021-02-13 22:14
Won't do. This is custom behavior which is need to be handled on app side. Seems like duplicate of https://github.com/jhomlala/betterplayer/issues/117

**Closed by jhomlala** 2021-02-13 22:14 UTC
Labels: enhancement, new issue

**Comment by SinoMiles** [comment] 2021-08-12 05:17
@YazeedAlKhalaf  how did you solve this problem? Auto full screen.
