### ISSUE TITLE
Better player controller does not Resume playback on Android when you have two or more controller instances running at the same-time. Trying to Resume video makes it restart.. 

### ISSUE THREAD

**Issue by AhabweEmmanuel** [jhomlala/betterplayer#643] opened 2021-08-08 18:39 UTC
On Android, the Better player controller does not Resume playback when you have two or more controller instances running. When you switch between the instances, trying to Resume the video of the first controller will make it restart. This bug is only on ANDROID. IOS works fine.

To reproduce this issue, create two better player controller instances and try to switch between them. When you try to  resume video playback of the first controller, playback will instead restart.

Expected Behaviour
Video Controller instances on Android should not share resources. Each controller instance should be independent of the other.

**Comment by jhomlala** [comment] 2021-08-09 17:24
@AhabweEmmanuel Please fill issue ticket properly and provide minimal reproducible example.

**Comment by jhomlala** [comment] 2021-08-15 17:47
No reply from author. Closing.

**Comment by lcdsmao** [comment] 2021-08-18 00:55
I also have this problem and noticed it happened when I forgot to set the aspect ratio.

Here is the reproducible example code:
```dart
import 'package:better_player/better_player.dart';
import 'package:better_player_example/constants.dart';
import 'package:flutter/material.dart';

class TwoControllersPage extends StatefulWidget {
  @override
  _TwoControllersPageState createState() => _TwoControllersPageState();
}

class _TwoControllersPageState extends State<TwoControllersPage> {
  late BetterPlayerController _betterPlayerController1;
  late BetterPlayerController _betterPlayerController2;

  @override
  void initState() {
    super.initState();
    _betterPlayerController1 = _createController();
    _betterPlayerController2 = _createController();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Two Controllers"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(controller: _betterPlayerController1),
          ),
          const SizedBox(height: 8),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(controller: _betterPlayerController2),
          ),
        ],
      ),
    );
  }

  BetterPlayerController _createController() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
      // aspectRatio: 16 / 9, // uncomment this and there will be no problem
      fit: BoxFit.contain,
    );
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      Constants.elephantDreamStreamUrl,
    );
    final betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    betterPlayerController.setupDataSource(dataSource);
    return betterPlayerController;
  }
}
```

**Comment by lcdsmao** [comment] 2021-08-18 01:31
And I also need to set launchMode to singleTask for successfully resumeing to fullscreen mode
```
            android:launchMode="singleTask"
```

**Comment by jhomlala** [comment] 2021-08-22 18:08
@lcdsmao What's the issue here? Can you record video where you'll present that issue? Or at least provide steps with description. I've tried to run the example, tested by clicking on "Open with same url", "Open with different url" and previous and new BP controller were working fine.

**Comment by lcdsmao** [comment] 2021-08-23 13:20
Hi @jhomlala 
I record some videos that present this issue.
I can reproduce with different devices in both debug and release build.
After some search of `adb log`, I didn't notice any useful crash log that may be related to this (not very sure).
PS. I have tried multiple times with "Open with different url" and can't reproduce this. 

Pixel 4a:

https://user-images.githubusercontent.com/13031690/130452891-a6d2abe2-5030-4eec-8a58-e1a44fe97943.mp4

SH-RM15:

https://user-images.githubusercontent.com/13031690/130451424-b579487a-3d2e-4511-b4fe-b924f15309d5.mp4

https://user-images.githubusercontent.com/13031690/130451492-e27d548f-584e-4a65-b8b7-ee072e4034bb.mp4

**Comment by jhomlala** [comment] 2021-08-24 20:11
I think you should be able to get crash logs in logcat in Android Studio. 
This siutation may be related to OOM crash. Can you try lower values in `BetterPlayerBufferingConfiguration` in data source configuration? Can you use other data source with some shorter video?

**Comment by lcdsmao** [comment] 2021-08-31 08:20
@jhomlala 
Thanks, it seems to set the BetterPlayerBufferingConfiguration to lower values solves this problem.

**Closed** 2021-08-31 19:39 UTC
Labels: info required

**Comment by umairali4433** [comment] 2023-01-14 22:17
I do have a question. how can we resume the last video? Scenario: if one video is playing and the second video comes up in between the first video after the completion I want to resume the first video how can I do that using betterplayercontroller.
