### ISSUE TITLE
[BUG] Video play back error m3u8

### ISSUE THREAD

**Issue by khanna007** [jhomlala/betterplayer#449] opened 2021-04-24 14:15 UTC
**Example code**
```dart
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';

import 'package:video_player/video_player.dart';

class VideoPage extends StatefulWidget {
  final Map map;

  const VideoPage({Key key, this.map}) : super(key: key);

  // final VideoPlayerController controllerVideo;
  //
  //  const VideoPage({Key key, this.controllerVideo}) : super(key: key);

  @override
  _VideoPagePageState createState() => _VideoPagePageState();
}

class _VideoPagePageState extends State<VideoPage> {
  BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    super.initState();
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      widget.map['playback']['hls'],
      hlsTrackNames: ["Low quality", "Not so low quality", "Medium quality"],
    );
    _betterPlayerController = BetterPlayerController(
      BetterPlayerConfiguration(),
      betterPlayerDataSource: betterPlayerDataSource,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 110,
      margin: EdgeInsets.only(left: 10, top: 20, bottom: 20),
      child: AspectRatio(
        aspectRatio: 1 / 1,
        child: BetterPlayer(
          controller: _betterPlayerController,
        ),
      ),
    );
  }
}

```
**Better Player version**
- Version:  better_player: ^0.0.64

**Additional context**
```
Playback error
E/ExoPlayerImplInternal(10515):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal(10515):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(10515):       at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal(10515):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(10515):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
E/ExoPlayerImplInternal(10515):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10515):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal(10515):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal(10515):       at java.lang.Thread.run(Thread.java:761)
E/flutter (10515): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (10515): 
```

**Comment by jhomlala** [comment] 2021-04-25 10:33
Please format your code next time. From the logs that you've provided it's clear that player can't access video. The error is 404. Please check if your video is accessible (you may check another player for example here: https://demo.theoplayer.com/test-your-stream-with-statistics)

**Comment by cngeru** [comment] 2021-04-26 13:24
Getting the same error... Works fine on browser tab. Fails in better_player and the site provided

**Comment by cngeru** [comment] 2021-04-26 17:54
Add this to your manifest .xml
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>

```

**Comment by jhomlala** [comment] 2021-04-26 19:37
@cngeru If someone can't give minimal reproducible example (and the source of video) then I can't debug it on my side. I can give only general tips which may lead to solving issue. Setup of manifest in Android is basic stuff and I assumed that you've already did that. Example app within this repo is good start for testing Better Player if something doesn't work.

**Comment by BibyChacko** [comment] 2021-04-26 21:36
@jhomlala  BetterPlayer.network(
          "${ApiLaunch.courseVideoFile + youtubeVideoModel.videofileName}",
          betterPlayerConfiguration: BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
          ),
        )

The url is working fine. its ending with .mp4 format

**Comment by jhomlala** [comment] 2021-04-27 16:56
@BibyChacko Your comment is not connected with original issue. Create new issue (remember to fill issue template correctly).

**Comment by Allan-Nava** [comment] 2021-04-29 07:46
it supports the hls format ?

**Comment by jhomlala** [comment] 2021-04-29 16:23
@Allan-Nava Please read the documentation. It won't be hard to find that information.

I'm closing this issue because it's going in wrong way. If someone need help then please create issue ticket and fill it properly.

**Closed by jhomlala** 2021-04-29 16:23 UTC
Labels: info required

**Comment by jenniestrongbow** [comment] 2021-07-09 07:57
The issue is not resolved. Why close it?

**Comment by jhomlala** [comment] 2021-07-09 08:04
@jenniestrongbow Did you read through issue? Author of the issue didn't provide minimal reproducible example and other people started reporting new issues. Please read through page next time.

**Comment by hashimraza** [comment] 2021-07-10 20:59
@jenniestrongbow getting the same error. did you find the solution?
