### ISSUE TITLE
[BUG] HLS Stream not playing in Android

### ISSUE THREAD

**Issue by jaredgermano** [jhomlala/betterplayer#735] opened 2021-09-29 15:53 UTC
**History check**
I did find similar issues, but they weren't very well thought out issues and most were closed without resolution.

**Describe the bug**
HLS stream is failing to play on Android. I'm getting the below exception from exoplayer, which implies it may not be a problem with better_player exactly, but this stream plays on other players. The stream URL is the following: https://api.beta.cadlearning.com/v1/Resources/VideoPublic?videoId=189885&thisisrequired=.m3u8

and I've tried this URL in https://demo.theoplayer.com/test-your-stream-with-statistics as well as https://players.akamai.com/players/hlsjs?streamUrl=https%3A%2F%2Fapi.beta.cadlearning.com%2Fv1%2FResources%2FVideoPublic%3FvideoId%3D189885%26thisisrequired%3D.m3u8 

and the stream plays fine there, as well as on the videojs player. I haven't tried it with this exact url, but we have a xamarin project that uses similar URLs with exoplayer and it works there as well in our production app.

Doing some brief debugging, it appears that better_player is in fact loading the m3u8, but I can't isolate the problem after that.

The exception is below:

E/ExoPlayerImplInternal( 9684): Playback error
E/ExoPlayerImplInternal( 9684):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9684):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal( 9684):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9684):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 9684):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9684):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal( 9684):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal( 9684):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
E/ExoPlayerImplInternal( 9684):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
E/ExoPlayerImplInternal( 9684):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

**To Reproduce**
Run the provided app below. If that doesn't work I can provide the code in a comment.

**Example code*
[better_player_test.zip](https://github.com/jhomlala/betterplayer/files/7253274/better_player_test.zip)

**Expected behavior**
The HLS stream should play.

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.60.1)
[√] Connected device (3 available)

• No issues found!

**Better Player version**
- Version: 0.0.76

**Smartphone (please complete the following information):**
 - Device: Pixel C
 - OS: Android 11

Let me know

**Comment by jhomlala** [comment] 2021-09-29 16:00
@jaredgermano https://jhomlala.github.io/betterplayer/#/datasourceconfiguration Please add videoFormat parameter to your data source.

**Comment by jaredgermano** [comment] 2021-09-29 19:08
@jhomlala Thanks for the quick response. That did get the video to play. I didn't see that property in the HLS examples, or I somehow missed it.

Now, however, subtitles aren't showing while they're part of the HLS stream and I believe it's because it expects the URL in the captions playlist to be a relative url. In my case, it's absolute (Let me know if I should open a new issue for this):

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:31
#EXTINF:31.000000
https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001 (1)-EN.vtt?sv=2018-03-28&sr=b&sig=vW5vp5bRbtCaG9IRt434LdVJfI%2BALZ5NtKM8fF%2BGtlA%3D&se=2021-09-29T19%3A07%3A11Z&sp=r
#EXT-X-ENDLIST

So when it uses the realUrl it looks like this: 

https://api.beta.cadlearning.com/v1/resources/https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001 (1)-EN.vtt?sv=2018-03-28&sr=b&sig=vW5vp5bRbtCaG9IRt434LdVJfI%2BALZ5NtKM8fF%2BGtlA%3D&se=2021-09-29T19%3A07%3A11Z&sp=r

Which isn't correct in this case. Do you have any advice on this?

**Comment by jhomlala** [comment] 2021-09-29 19:48
BP tries to read subtitles from this link:

```
https://api.beta.cadlearning.com/v1/resources/https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001 (1)-EN.vtt?sv=2018-03-28&sr=b&sig=%2B%2FjP9tplnfzI2Y76i8LTN97D1vF%2FgZ1DEPYI1R5lzho%3D&se=2021-09-29T19%3A52%3A09Z&sp=r
```
This url returns 404.

**Comment by jaredgermano** [comment] 2021-09-29 22:01
That's because, as I said, it's the wrong link. The link should be: https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001 (1)-EN.vtt?sv=2018-03-28&sr=b&sig=vW5vp5bRbtCaG9IRt434LdVJfI%2BALZ5NtKM8fF%2BGtlA%3D&se=2021-09-29T19%3A07%3A11Z&sp=r

See how it's concatenating the main url for the playlist and the url for the captions? BP is trying to create a url from the captions url in the captions m3u8 and the primary url for the m3u8. That is, it's prepending https://api.beta.cadlearning.com/v1/resources/ when it shouldn't be.

**Comment by jhomlala** [comment] 2021-09-30 18:56
You should remove this space from subtitle link and everything will work fine. Better Player works as intended and if there's space in your url then it's being replaced by `%20` which seems like is not supported by your server (I don't know why).
Also from my experience is better to have url without any special characters. 

```https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001 (1)-EN.vtt?sv=2018-03-28&sr=b&sig=vW5vp5bRbtCaG9IRt434LdVJfI%2BALZ5NtKM8fF%2BGtlA%3D&se=2021-09-29T19%3A07%3A11Z&sp=r
```
Should be changed to:
```
https://casabeta.blob.core.windows.net/captions/755023.734723.acad17c0001t0001(1)-EN.vtt?sv=2018-03-28&sr=b&sig=vW5vp5bRbtCaG9IRt434LdVJfI%2BALZ5NtKM8fF%2BGtlA%3D&se=2021-09-29T19%3A07%3A11Z&sp=r
```

**Comment by jhomlala** [comment] 2021-09-30 19:13
I didn't see previously HLS data source with full url path to the subtitle. Anyway you can try this fix:
```
    git:
      url: https://github.com/jhomlala/betterplayer
      ref: bugfix/full_url_subtitle_fix
```

**Comment by jaredgermano** [comment] 2021-09-30 20:00
Yep, this fixes it. I know it's probably not the normal way to do it, but unfortunately our captions are on another server so it has to be a full url.

Thanks a lot for your time!

**Comment by jhomlala** [comment] 2021-11-03 20:58
This will be included in next PR which comes with this branch: https://github.com/jhomlala/betterplayer/tree/feature/november_2021_changes

**Comment by jhomlala** [comment] 2021-11-07 09:36
Added in 0.0.78.

**Closed by jhomlala** 2021-11-07 09:36 UTC
Labels: bug
