### ISSUE TITLE
[FEATURE] Support for web

### ISSUE THREAD

**Issue by pratik7span** [jhomlala/betterplayer#734] opened 2021-09-29 10:52 UTC
Please give support of Web especially for HLS (m3u8) Videos because no one is providing resolution changing feature.

**Describe the solution you'd like:**
There are many players which are good but better player is really amazing. There is a missing thing especially web support.

**Comment by jhomlala** [comment] 2021-09-29 16:26
@pratik7span Duplicate of https://github.com/jhomlala/betterplayer/issues/369. Please use search function next time.

**Closed by jhomlala** 2021-09-29 16:26 UTC
Labels: enhancement, new issue
