### ISSUE TITLE
[BUG] Rotating screen problem

### ISSUE THREAD

**Issue by levent-kantaroglu** [jhomlala/betterplayer#440] opened 2021-04-20 09:55 UTC
**Describe the bug**
I get this error:
```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for VideoPlayerController:
setState() or markNeedsBuild() called when widget tree was locked.

This BetterPlayerSubtitlesDrawer widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: BetterPlayerSubtitlesDrawer
    state: _BetterPlayerSubtitlesDrawerState#87656
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
package:flutter/…/widgets/framework.dart:4143
#1      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4153
```

**To Reproduce**
1. I access to my downloas page. It contains a player and videolist
2. I click on a video to play
3. It starts playing
4. when I rotate screen, I get that error.

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**
Before this plugin's null safety migration. My code was working successfully

**Screenshots**

**Flutter doctor**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-x64, locale en-TR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 4.1)
> [✓] VS Code (version 1.55.2)
> [✓] Connected device (3 available)

**Better Player version**
- Version: ^0.0.63

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: [e.g. iOS14]

**Comment by jhomlala** [comment] 2021-04-21 18:17
Please provide minimal reproducible code which I can run on my side. I assume that your widget got disposed when your screen rotates. Without code I can't help you.

**Comment by acavazos1982** [comment] 2021-04-27 23:20
I get this exact same problem when trying to play in small screen a video and then doing full screen on user click.

The culprit is at better_player/src/subtitles/better_player_subtitles_drawer.dart:93:7)

the problem is when i try to rebuild the interfase from small video to big video it crashes with the setState on the updating method.

`  ///Called when player state has changed, i.e. new player position, etc.
  void _updateState() {
    if (mounted) {
      setState(() {
        _latestValue =
            widget.betterPlayerController.videoPlayerController!.value;
      });
    }
  }`

**Comment by jhomlala** [comment] 2021-04-29 16:40
@levent-kantaroglu @acavazos1982 I ask again - please attach minimal reproducible code. This is last call. If you won't respond with any code I'll close this issue.

**Comment by jhomlala** [comment] 2021-05-08 07:39
Closed - author didn't provide minimal reproducible example.

**Closed by jhomlala** 2021-05-08 07:39 UTC
Labels: info required

**Comment by levent-kantaroglu** [comment] 2021-06-08 07:17
Problem is still going on, here is code to run
```

import 'dart:io';

import 'package:better_player/better_player.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:path_provider/path_provider.dart';
import 'package:mobile/commons/functions.dart';
import 'package:mobile/commons/handle_exception.dart';
import 'package:mobile/commons/scope_models/scoped_model.dart';
import 'package:mobile/view/common/custom_app_bar.dart';
import 'package:video_player/video_player.dart';

import 'download_controller.dart';

class DownloadedVideosPage2 extends StatefulWidget {
  const DownloadedVideosPage2({Key? key}) : super(key: key);

  @override
  _DownloadedVideosPage2State createState() => _DownloadedVideosPage2State();
}

class _DownloadedVideosPage2State extends State<DownloadedVideosPage2> {
  bool isLoading = true;
  List downloadItems = [];
  bool isPlayerVisible = false;
  BetterPlayerController betterPlayerController =
      BetterPlayerController(BetterPlayerConfiguration());

  @override
  void initState() {
    prepareDownloadTasks();
    super.initState();
  }


  void playVideo(DownloadItem downloadItem) async {
    if (!isPlayerVisible) {

      setState(() {
        isPlayerVisible = true;
      });
    }
    var filename =
        "${downloadItem.task.savedDir}/${downloadItem.task.filename}";
    var file = File(filename);
    bool doesFileExist = await file.exists();
    printData("doesFileExist", doesFileExist);
    if (!doesFileExist) {
      printError("$filename not exists", "downloaded file not exist");
    } else {
      file.stat();
      betterPlayerController
          .setupDataSource(BetterPlayerDataSource.file(filename));
      betterPlayerController.play();
    }
  }

  void prepareDownloadTasks() async {
    setState(() {
      isLoading = true;
    });

    final _directory = await getApplicationDocumentsDirectory();
    final downloadController = DownloadController(_directory.path.toString());

    try {
      downloadItems = await downloadController.loadTasks();

      for (var downloadItem in downloadItems) {}
    } catch (e, stackTrace) {
      handleException(
          error: e, stackTrace: stackTrace, tag: 'prepare download Page');
      print("err: " + e.toString());
    }

    setState(() {
      isLoading = false;
    });
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBars.appBar(
        context: context,
        label: "Downloads",
      ),
      body: (isLoading) ? loaderIndicator : body(),
    );
  }

  Widget body() {
    // online case
    if (AppState.of(context).online) {
      return downloadItems.length == 0 ? noVideoWidget : contentWidgets;
    }
    // offline case
    else {
      return downloadItems.length == 0 ? emptyList : contentWidgets;
    }
  }

  Widget get loaderIndicator => Center(
        child: Theme(
            data: ThemeData(accentColor: Colors.purple),
            child: CircularProgressIndicator()),
      );

  Widget get contentWidgets {
    return (MediaQuery.of(context).orientation == Orientation.portrait)
        ? portraitDesign
        : landscapeDesign;
  }

  Widget get videoPlayerWidget {
    return BetterPlayer(
  
      controller: betterPlayerController,
    );
  } 

  Widget get portraitDesign {
    return Column(
      children: <Widget>[
        if (isPlayerVisible) videoPlayerWidget,
        const SizedBox(height: 5),
        Container(
          child: Flexible(
            child: downloadListItemWidgets,
          ),
        ),
      ],
    );
  }

  Widget get landscapeDesign {
    return Row(
      children: [
        if (isPlayerVisible)
          Expanded(
            child: Column(
              children: [
                AspectRatio(
                  aspectRatio: 16 / 9,
                  child: videoPlayerWidget,
                ),
              ],
            ),
          ),
        Expanded(
          child: Container(
            padding: EdgeInsets.only(left: 5, top: 5),
            child: downloadListItemWidgets,
          ),
        ),
      ],
    );
  }

  Widget downloadListItemWidget(DownloadItem downloadItem) {
    if (downloadItem.status == DownloadTaskStatus.complete)
      return completedDownloadListItem(downloadItem);
    else
      return FlutterLogo(); // fix it
  }

  List<Widget> videoTitles(DownloadItem downloadItem) {
    final List<Widget> titles = <Widget>[];
    if (downloadItem.video.title != '') {
      titles.add(videoTitle(downloadItem.video.title));
    }

    if (downloadItem.video.project != null) {
      if (downloadItem.video.project?.title != null &&
          downloadItem.video.project?.title != '') {
        titles.add(projectTitle(downloadItem.video.project!.title));
      }
    }
    return titles;
  }

  Widget videoTitle(String text) {
    return Text(
      text,
      maxLines: 2,
      overflow: TextOverflow.ellipsis,
      style: TextStyle(
        fontWeight: FontWeight.w500,
        fontSize: 15.0,
      ),
    );
  }

  Widget projectTitle(String text) {
    return Text(
      text,
      maxLines: 1,
      overflow: TextOverflow.ellipsis,
      style: TextStyle(
        fontSize: 14.0,
        color: Colors.grey,
      ),
    );
  }

  Widget completedDownloadListItem(DownloadItem downloadItem) {
    final List<Widget> titles = <Widget>[];
    if (downloadItem.video.title != '') {
      titles.add(Text(
        downloadItem.video.title,
        maxLines: 2,
        overflow: TextOverflow.ellipsis,
        style: TextStyle(
          fontWeight: FontWeight.w500,
          fontSize: 15.0,
        ),
      ));
    }

    if (downloadItem.video.project != null) {
      if (downloadItem.video.project?.title != null &&
          downloadItem.video.project?.title != '') {
        titles.add(Text(
          downloadItem.video.project!.title,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: TextStyle(
            fontSize: 14.0,
            color: Colors.grey,
          ),
        ));
      }
    }
    return Container(
      child: InkWell(
        onTap: () => playVideo(downloadItem),
        child: Container(
            child: new Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const SizedBox(width: 8),
            Expanded(
              flex: 1,
              child: Container(
                color: Colors.black,
                child: ConstrainedBox(
                  constraints: const BoxConstraints(),
                  child:
                      CachedNetworkImage(imageUrl: downloadItem.video.imageUrl),
                ),
              ),
            ),
            Expanded(
              flex: 2,
              child: Container(
                margin: const EdgeInsets.only(left: 10.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: titles,
                ),
              ),
            ),
     
          ],
        )),
      ),
    );
  }

  Widget get downloadListItemWidgets {
    return GridView(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          childAspectRatio: 4.5,
          crossAxisCount:
              (MediaQuery.of(context).orientation == Orientation.portrait)
                  ? 1
                  : isPlayerVisible
                      ? 1
                      : 2),
      children: downloadItems
          .map(
            (downloadItem) => Container(
              margin: const EdgeInsets.only(bottom: 10.0),
              child: downloadListItemWidget(downloadItem),
            ),
          )
          .toList(),
    );
  }

  Widget get noVideoWidget {
    return emptyList
     ;
  }

  Widget get emptyList => Center(
        child: Text("No Video"),
      );

  
}

```
