### ISSUE TITLE
[FEATURE]how to realize the function of full screen screenshot?

### ISSUE THREAD

**Issue by devyueyue** [jhomlala/betterplayer#908] opened 2022-02-09 01:53 UTC
There is a demand for the app. When the video is played in full screen, it needs a screenshot. If the screenshot of the content of the video is not available, how to realize the function of full screen screenshot?

**Comment by jhomlala** [comment] 2022-04-25 17:13
Duplicate of https://github.com/jhomlala/betterplayer/issues/907

**Closed by jhomlala** 2022-04-25 17:13 UTC
Labels: enhancement, new issue
