### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by devyueyue** [jhomlala/betterplayer#1083] opened 2022-09-19 06:11 UTC
M3u8, no sound after dragging the progress bar

The m3u8 video file will often mute after dragging the progress bar, and there will be sound again later

**Comment by mis-kcn** [comment] 2022-09-19 13:19
Duplicate of https://github.com/jhomlala/betterplayer/issues/1082, should close this one.

**Comment by devyueyue** [comment] 2022-09-20 03:14
ok

**Closed** 2022-09-20 03:13 UTC
Labels: new issue
